model_path = "C:/Users/Jo/capstone/model/fa_xception_unfreeze.h5"
fa_path = "C:/Users/Jo/capstone/model/fa_xception_unfreeze.h5"
gochu_path = "C:/Users/Jo/capstone/model/gochu_xception_unfreeze.h5"
kong_path = "C:/Users/Jo/capstone/model/kong_xception_unfreeze.h5"
mu_path = "C:/Users/Jo/capstone/model/mu_xception_fine_tuning.h5"
bachu_path = "C:/Users/Jo/capstone/model/bachu_xception_fine_tuning.h5"